name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "release-*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test (windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
      - name: Build (release)
        run: cargo build --release --verbose --features rustls-tls
      - name: Check (release, lib+bins only)
        run: cargo check --release --verbose --features rustls-tls --lib --bins

  build-artifacts:
    name: Build release artifacts (windows)
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
      - name: Build (release)
        run: cargo build --release --verbose --features rustls-tls
      - name: Prepare artifact (Windows)
        shell: pwsh
        run: |
          New-Item -Path dist -ItemType Directory -Force | Out-Null
          Copy-Item -Path "target/release/appian-deployment-cli.exe" -Destination "dist/appian-deployment-cli-windows.exe" -Force
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: dist/*

  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build-artifacts
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-binary
          path: dist
      - name: Publish release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/appian-deployment-cli-windows.exe
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
